### ISSUE TITLE
Unable to call Shiny app for GO thresh

### ISSUE THREAD

**Issue by wk-chan** [jn-goe/gruffi#1]
Hi,

I've been trying to use this on my samples. It works fine until thresholding for GO term where I got this error:

In file(filename, "r", encoding = encoding) :
  cannot open file '/ui.R': No such file or directory

I had a look and I couldn't find the ui.R and server.R from the package. Can you please advise?

**Comment by vertesy** [comment]
Hello & thanks for trying out gruffi. The mistake was on our end, I now added the missing scripts in `/inst`!

Besides using `require(gruffi)`, could you please also `devtools::load_all(path = "~/your/path/to/gruffi/")` ? 
The ui function is loaded only this way at the moment .

**Comment by vertesy** [comment]
I assume it worked out.
