### ISSUE TITLE
Unable to load package

### ISSUE THREAD

**Issue by wk-chan** [jn-goe/gruffi#2]
Hello,

Firstly thank you for the tool. I've previously managed to run gruffi fine and it was helpful in better defining pseudotime for my dataset. However, recently I tried to run this again on another dataset but I was unable to load the package. Below is the error I'm getting:

Warning messages:
1: S3 method ‘plot.clust.size.distr’ was declared in NAMESPACE but not found 
2: In setup_ns_exports(path, export_all, export_imports) :
  Objects listed as exports, but not present in namespace: AddCustomScore, AddGOGeneList.manual, AddGOScore, CalcTranscriptomePercentage, CalcTranscriptomePercentageGO, CleanDuplicateScorenames, CustomScoreEvaluation, FeaturePlotSaveCustomScore, FeaturePlotSaveGO, FilterStressedCells, GO_score_evaluation, GetAllGOTerms, GetGOTerms, GetNamedClusteringRuns, IntersectWithExpressed, PasteUniqueGeneList, PlotGoTermScores, PlotNormAndSkew, Shiny.GO.thresh, UMAP.3d.cubes, aut.res.clustering, calc.cluster.averages.gruffi, clUMAP.thresholding, fix.metad.Colname.rm.trailing.1, reassign.small.clusters, saveData, saveRDS.compress.in.BG, sparse.cor, stand_dev_skewed, ww.convert.GO_term.2.score, ww.convert.score.2.GO_term

**Comment by vertesy** [comment]
Hi,

so these are _not errors,_ but warnings - meaning that the package was still loaded. 

Please download the latest version. For me both of these commands work without any warning or error:

```r
require(gruffi)
devtools::load_all(path = "~/GitHub/Packages/gruffi/")
```

Let me know if you still have the problem!

**Comment by wk-chan** [comment]
Thanks for getting back to me. I've removed the packages and tried to reinstall everything but now I've encountered this error while trying to install CodeAndRoll2:

Error: object ‘stopif’ is not exported by 'namespace:MarkdownReports'
Execution halted

resulting in me unable to install gruffi.

**Comment by vertesy** [comment]
Hi,

could you try below and see if you still have the error:
```r
devtools::install_github(repo = "vertesy/Stringendo", upgrade = F)
devtools::install_github(repo = "vertesy/ReadWriter", upgrade = F)
devtools::install_github(repo = "vertesy/CodeAndRoll2", upgrade = F)
devtools::install_github(repo = "vertesy/MarkdownHelpers", upgrade = F)
devtools::install_github(repo = "vertesy/MarkdownReports", upgrade = F)
```

Not sure why you got `Error: object ‘stopif’ is not exported by 'namespace:MarkdownReports'`, but I removed one part that may have caused it.

**Comment by wk-chan** [comment]
Hi, I've tried the following and I'm still having the error.

I'm not sure what is causing it.

**Comment by vertesy** [comment]
Hi, sorry for the late follow up! I now successfully installed it on three new computers, and updated some the dependencies, so I believe if you use the latest versions, you should be fine. Sorry for your troubles with getting it to run.
