### ISSUE TITLE
i cannot seem to load the package

### ISSUE THREAD

**Issue by deevdevil88** [jn-goe/gruffi#3]
hi!
I manage to install the package fine , but when i do 
`devtools::load_all(path = "/Library/Frameworks/R.framework/Versions/Current/Resources/library/gruffi/")`

i get the same error as  #2 . i am sorry but what should I do to solve this?

Devika

**Comment by deevdevil88** [comment]
Nevermind, i know what the issue was. I think you need to clarify in your README, that the path for `devtools::load_all`  isnt to the installed gruffi package location in the R folder, but the location to where the github package has been cloned.
As when i changed the path to latter, it worked fine.
Best,
Devika

**Comment by vertesy** [comment]
Thank you, I changed it now!
