### ISSUE TITLE
How important is it to have negative filters

### ISSUE THREAD

**Issue by deevdevil88** [jn-goe/gruffi#4]
Hi,
I had a question, im using the gruffi package to identify stressed vs non-stressed cells in my human iPSC DaNs 10x data. 
I have read the pre-print for gruffi and i see why negative filtering was gliogenesis was implemented. 
Since in my case neurogenesis or cell differentiation would be a better negative filter I included those. 

However, i was wondering do i definitely need to have a negative filter? 
If i decided to not use a negative filter for neurogenesis, true i might be identifying real neurons which have difference in the stressed pathways because of my treatment, but in your experience how much difference does not including a negative filter make. 
Or rather how should I then interpret the results?

Best,
Devika

**Comment by vertesy** [comment]
Dear Devika, 

sorry for getting back late, I had a traffic accident. I guess may not be helpful now, nevertheless:

- **Do not use a negative filter, if it's not clearly needed** 
- You only need it if some of your biological signatures correlates with the signatures you want to filter out (e.g glia have higher _physiological_ ER stress than other cells).

In your concrete case, if you have evidence that neurogenesis correlates with ER-stress or glycolysis, then it is necessary to use it (I would guess it would not).

Best
Abel

**Comment by deevdevil88** [comment]
Thank you @vertesy . I hope you are ok now since your accident. I guess in my case I was worried that treated iPSC cells might get identified as stressed, because of the phenotype of the treatment. So that's  why I did a negative filter for neurogenesis, as these cells would still be high for cell development /neurogenesis but could have ER stress because of the treatment.

**Comment by vertesy** [comment]
I guess _if you see_ evidence that you identify more stressed cells _among your treated neurons_, then I would use it. 
I would however try to identify what genes are activated by your treatment, and try to exclude those from the stress analysis -  but increased stress may be a 'positive' readout of your treatment.
