### ISSUE TITLE
Automatic execution of Shiny app

### ISSUE THREAD

**Issue by heylf** [jn-goe/gruffi#6]
@vertesy 

The Gruffi tool is very useful, but I need it in a completely automatic fashion, leading to the following question. Would it be possible to set the thresholds for the three GO terms without the Shiny app (e.g., just push the button save thresholds immediately after start of the shiny app)?

**Comment by vertesy** [comment]
Yes, it is possible. Let me get back on this in the coming days.

Best Wishes,
Ábel

**Comment by heylf** [comment]
@vertesy 

https://github.com/jn-goe/gruffi/pull/7

**Comment by vertesy** [comment]
Thank you!  Solved now with PR merge.  See details in #7.
