### ISSUE TITLE
Still unclear how to install

### ISSUE THREAD

**Issue by michallipinski** [jn-goe/gruffi#9]
Hi,
I'm very excited about trying gruffi as I think it could resolve some issues I've been observing with the pseudotime analysis. Unfortunately I've been following your installation and it is still unclear for me how to make the package work. I get a similar warning as in the resolved issue #2 but I don't understand what the solution actually is. I'm not a trained computational biologist, more an advanced amateur so an implied answer didn't really help me.
This is the warning I get:
> devtools::load_all("/Library/Frameworks/R.framework/Versions/4.2/Resources/library/gruffi/")

> ℹ Loading gruffi
> Warning messages:
> 1: S3 method ‘plot.clust.size.distr’ was declared in NAMESPACE but not found 
> 2: Objects listed as exports, but not present in namespace:
> • AddCustomScore
> • AddGOGeneList.manual
> • AddGOScore
> • CalcTranscriptomePercentage
> • CalcTranscriptomePercentageGO
> • CleanDuplicateScorenames
> • CustomScoreEvaluation
> • FeaturePlotSaveCustomScore
> • FeaturePlotSaveGO
> • FilterStressedCells
> • GO_score_evaluation
> • GetAllGOTerms
> • GetGOTerms
> • GetNamedClusteringRuns
> • IntersectWithExpressed
> • PasteUniqueGeneList
> • PlotGoTermScores
> • PlotNormAndSkew
> • Shiny.GO.thresh
> • UMAP.3d.cubes
> • aut.res.clustering
> • calc.cluster.averages.gruffi
> • clUMAP.thresholding
> • fix.metad.Colname.rm.trailing.1
> • reassign.small.clusters
> • saveData
> • saveRDS.compress.in.BG
> • sparse.cor
> • stand_dev_skewed
> • ww.convert.GO_term.2.score
> • ww.convert.score.2.GO_term 

The `install_github` functions like `devtools::install_github(repo = "vertesy/Stringendo", upgrade = F)` install them in the same folder "/Library/Frameworks/R.framework/Versions/4.2/Resources/library/", so I really don't know what I'm supposed to "load_all".
I'd appreciate any help. Thank you!
Michal

**Comment by jn-goe** [comment]
Hi Michal, 

thanks for your message! Apparently there was a problem with the function naming when building the R package. With the latest update the problem should be fixed. Can you try to reinstall gruffi and check if the error still occurs?
```
devtools::install_github(repo = "jn-goe/gruffi", force = TRUE)
```
Best, 
Julia
